apiVersion: v1
kind: Secret
metadata:
  name: appd-secret
type: Opaque
data:
  #base64 encoded APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY (echo -n <keyvalue>|base64)
  APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: 
